### ISSUE TITLE
File Name Option

### ISSUE THREAD

**Issue by FrankBiedermann** [ComPlat/Thermosimfit#11]
Hello Konrad,

For the result file download, it would be good to have two options:

1) Your naming as it is right now.

2) Alternative option (maybe via Tick-Box):  File name of Results should contain the file name of the original data file that was uploaded

Thanks
Frank

**Comment by Konrad1991** [comment]
Hi Frank, 

I would suggest to add the filename as an information in the result file. Furthermore, the dataset itself could be stored. Is this ok?

Best Konrad

**Comment by FrankBiedermann** [comment]
Yes, sounds good

 

Von: Konrad ***@***.***>
Antworten an: ComPlat/Thermosimfit ***@***.***>
Datum: Dienstag, 13. August 2024 um 08:40
An: ComPlat/Thermosimfit ***@***.***>
Cc: Frank Biedermann ***@***.***>, Author ***@***.***>
Betreff: Re: [ComPlat/Thermosimfit] File Name Option (Issue #11)

 

Hi Frank,

I would suggest to add the filename as an information in the result file. Furthermore, the dataset itself could be stored. Is this ok?

Best Konrad
