### ISSUE TITLE
Plot display

### ISSUE THREAD

**Issue by FrankBiedermann** [ComPlat/Thermosimfit#15]
Hallo Konrad,

![Bildschirmfoto 2024-08-21 um 23 39 14](https://github.com/user-attachments/assets/33cc3c85-4e0a-4d64-8c10-42034338eb5d)

Die lila Kurve für measured ist etwas verwirrend, wenn mehrere Datensätze zusammen dargestellt werden.

**Comment by Konrad1991** [comment]
Wäre diese darstellung besser?

![image](https://github.com/user-attachments/assets/585ef8a0-8180-4a2d-8423-7e470a984c6f)
