### ISSUE TITLE
Plotting 

### ISSUE THREAD

**Issue by FrankBiedermann** [ComPlat/Thermosimfit#20]
Hallo Konrad,

- [ ] Wenn beim Single-Analysis Tab der Plot am Ende ähnlich zum Batch Tab aussehen kann (z.B. graue Linie/Punkte für experimentelle Daten), wäre das gut.

- [ ] Mir ist aufgefallen, dass bei sehr guten Fit die Experimentellen Datenpunkte die gefitteten Pubkte im Batch Mode Plot überdecken. Weiß nicht, wie man das besser machen kann, aber zur Info

**Comment by Konrad1991** [comment]
Ich habe die dots nun transparent gemacht, dadurch wird es dunkler bei überlappung. Ist jetzt nur für die Einzeloptimierung möglich
