### ISSUE TITLE
Plotting Display

### ISSUE THREAD

**Issue by FrankBiedermann** [ComPlat/Thermosimfit#21]
Hallo Konrad,

Beim Batch Mode verabschiedet sich Plot des Dataset 4 in der Darstellung über den linken Rand.
![Bildschirmfoto 2024-08-27 um 17 19 59](https://github.com/user-attachments/assets/4781dc8e-48bb-48e5-a61b-9992f14e1dd7)

 Bild anbei

Evt nur 3 Bilder nebeneinander darstellen? Größe der Einzelplots ist gut.

Grüße
Frank

**Comment by Konrad1991** [comment]
Ich habs für IDA gefixt. Die Höhe ist auch gut aber bei unter 4 Datensets habe ich eine Lücke zu den unterne Plots und ich weiß noch nicht warum

**Comment by vmahram** [comment]
Hello Konrad, 
I have some suggestions:
I think it would be better if you consider the green dot as a measure of data and the grey line as a fitting prediction. but this is the opposite in the software
![image](https://github.com/user-attachments/assets/743af4ae-4c40-43e4-80b9-48985b5a29fa)

**Comment by vmahram** [comment]
I think it would be much better in the first graph (from the top), you show the colours of the repetitions in the graph, if you have a look, it is completely grey. it is not clear in that graph the line of the fitting is the result of 3 times repetitions of analysis.
![image](https://github.com/user-attachments/assets/57827d7d-8e78-4255-a35a-39c0b067074e)

**Comment by vmahram** [comment]
the final picture of the analysis (I mean in the Excel file) doesn't have high quality, especially if we want to use it for a presentation... could you please change the resolution of that (use a higher resolution with a standard dpi)? 
![image](https://github.com/user-attachments/assets/a4055c21-14cb-4737-acef-6e17843495e7)
![image](https://github.com/user-attachments/assets/26e7e8ce-c244-4004-b9e8-f77da000e90a)

**Comment by Konrad1991** [comment]
> I think it would be better if you consider the green dot as a measure of data and the grey line as a fitting prediction. but this is the opposite in the software

I can easily change this.
